steps:
  - label: ":cat: cat README"
    command: "cat README.md"

  - label: ":partyparrot: hello world"
    command: "inline_image 'https://media0.giphy.com/media/8Ry7iAVwKBQpG/giphy.gif' 'Rainbows''"

  # - label: ":rspec: Unit tests"
  #   command: "echo 'I'm running unit specs - a lot of them'"

  # - label: ":cypress: Integration tests"
  #   command: "echo 'My integration tests are slooooow'"

  - wait

  # - label: ":terraform: Apply staging"
  #   command: "echo 'My first pipeline!!!'"

  # - label: ":aws: Deploy to staging"
  #   command: "echo 'My first pipeline!!!'"
