steps:
  - label: ":cat: cat README"
    command: "cat README.md"

  - label: ":partyparrot: hello world"
    command: "echo 'My first pipeline!!! '"

  - label: ":lint-roller: Linting"
    command: "echo 'linting all the files'"

  - group: ":sleuth_or_spy: Tests"
    key: "tests"

    steps:
    - label: ":rspec: Unit tests"
      parallelism: 5
      command: "echo 'I'm running unit specs - parallelising means they'll run across 5 agents and finish faster'"

    - label: ":cypress: Integration tests"
      parallelism: 5
      command: "echo 'My integration tests are slooooow'"

  - wait

  - block: ":woman-raising-hand: Block step"

  - input: "Who goes there?"
    fields:
      - text: "Your name"
        key: "name"

      - select: "Your team"
        key: "teams"
        options:
          - label: "Customer Support"
            value: "Pipelines"
          - label: "Marketing"
            value: "Foundation"

  - group: ":woman-tipping-hand: Deploy to Staging"
    key: "staging-deploy"
    depends_on: "tests"

    steps:
      - label: ":terraform: Plan staging"
        command: "echo 'can we create all the things?'"
      - label: ":terraform: Apply staging"
        command: "echo 'yes please create all the things!'"
      - label: ":aws: Deploy to ECS staging"
        command: "echo ':rollercoaster: woot here are all the things!'"

  - group: ":shipit: Deploy to Production"
    depends_on: "staging-deploy"

    steps:
    - label: ":terraform: Plan production"
      command: "echo 'can we create all the things?'"
    - label: ":terraform: Apply staging"
      command: "echo 'yes please create all the things!'"
    - label: ":aws: Deploy to ECS staging"
      command: "echo ':passenger_ship: Here are all the things!'"